name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build `run` Docker image
      run: docker build . --file KexStandaloneRun --tag kex:$(date +%s)

    - name: Build `test` Docker image
      run: docker build . --file KexStandaloneTest --tag kex:$(date +%s)
